"""add_updated_at_to_claims

Revision ID: 3c0e82e1d503
Revises: 5a563a820e0d
Create Date: 2026-02-20 18:34:35.196058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c0e82e1d503'
down_revision: Union[str, None] = '5a563a820e0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column as nullable first
    op.add_column('claims', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # Set default value for existing rows (use created_at as initial value)
    op.execute("UPDATE claims SET updated_at = created_at WHERE updated_at IS NULL")
    # Now make it non-nullable
    op.alter_column('claims', 'updated_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claims', 'updated_at')
    # ### end Alembic commands ###
