"""initial_schema

Revision ID: 5a563a820e0d
Revises: 
Create Date: 2026-02-20 14:51:10.058876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a563a820e0d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('agent_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('graph_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index('ix_agent_sessions_session_id', 'agent_sessions', ['session_id'], unique=False)
    op.create_index('ix_agent_sessions_user_id', 'agent_sessions', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_actor', 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('policy_number', sa.String(length=128), nullable=False),
    sa.Column('claim_type', sa.String(length=32), nullable=False),
    sa.Column('claim_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('fraud_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('verified_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_claims_created_at', 'claims', ['created_at'], unique=False)
    op.create_index('ix_claims_status', 'claims', ['status'], unique=False)
    op.create_index('ix_claims_user_id', 'claims', ['user_id'], unique=False)
    op.create_table('consent_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('consent_version', sa.String(length=32), nullable=False),
    sa.Column('consent_text_hash', sa.String(length=128), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consent_created_at', 'consent_records', ['created_at'], unique=False)
    op.create_index('ix_consent_user_id', 'consent_records', ['user_id'], unique=False)
    op.create_table('user_fraud_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_claims', sa.Integer(), nullable=False),
    sa.Column('recent_claims_30d', sa.Integer(), nullable=False),
    sa.Column('last_claim_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_claim_amount_90d', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fraud_flag_count', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('uploader_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extraction_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('requires_manual_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_claim_id', 'documents', ['claim_id'], unique=False)
    op.create_index('ix_documents_uploader_id', 'documents', ['uploader_id'], unique=False)
    op.create_table('fraud_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('fraud_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('deterministic_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('statistical_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('behavioral_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('document_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('network_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('layer_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('layer_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('explanation_text', sa.Text(), nullable=True),
    sa.Column('feature_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('config_version', sa.String(length=32), nullable=True),
    sa.Column('ai_degraded_mode', sa.Boolean(), nullable=False),
    sa.Column('ml_model_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id')
    )
    op.create_index('ix_fraud_assessments_claim_id', 'fraud_assessments', ['claim_id'], unique=False)
    op.create_table('qr_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=256), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_qr_tokens_claim_id', 'qr_tokens', ['claim_id'], unique=False)
    op.create_index('ix_qr_tokens_token_hash', 'qr_tokens', ['token_hash'], unique=False)
    op.create_table('settlements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('initiated_by', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('settlement_reference', sa.String(length=128), nullable=True),
    sa.Column('external_reference', sa.String(length=256), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id'),
    sa.UniqueConstraint('settlement_reference')
    )
    op.create_index('ix_settlements_claim_id', 'settlements', ['claim_id'], unique=False)
    op.create_table('document_access_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_doc_access_document_id', 'document_access_logs', ['document_id'], unique=False)
    op.create_index('ix_doc_access_user_id', 'document_access_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_doc_access_user_id', table_name='document_access_logs')
    op.drop_index('ix_doc_access_document_id', table_name='document_access_logs')
    op.drop_table('document_access_logs')
    op.drop_index('ix_settlements_claim_id', table_name='settlements')
    op.drop_table('settlements')
    op.drop_index('ix_qr_tokens_token_hash', table_name='qr_tokens')
    op.drop_index('ix_qr_tokens_claim_id', table_name='qr_tokens')
    op.drop_table('qr_tokens')
    op.drop_index('ix_fraud_assessments_claim_id', table_name='fraud_assessments')
    op.drop_table('fraud_assessments')
    op.drop_index('ix_documents_uploader_id', table_name='documents')
    op.drop_index('ix_documents_claim_id', table_name='documents')
    op.drop_table('documents')
    op.drop_table('user_fraud_profiles')
    op.drop_index('ix_consent_user_id', table_name='consent_records')
    op.drop_index('ix_consent_created_at', table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index('ix_claims_user_id', table_name='claims')
    op.drop_index('ix_claims_status', table_name='claims')
    op.drop_index('ix_claims_created_at', table_name='claims')
    op.drop_table('claims')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_index('ix_audit_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_actor', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_agent_sessions_user_id', table_name='agent_sessions')
    op.drop_index('ix_agent_sessions_session_id', table_name='agent_sessions')
    op.drop_table('agent_sessions')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
