"""add updated_at to all tables

Revision ID: cdfe9f7e2021
Revises: 5a563a820e0d
Create Date: 2026-02-20 19:08:27.966119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdfe9f7e2021'
down_revision: Union[str, None] = '5a563a820e0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('claims', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.add_column('consent_records', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('document_access_logs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('fraud_assessments', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('qr_tokens', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_fraud_profiles', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('user_fraud_profiles', 'updated_at')
    op.drop_column('qr_tokens', 'updated_at')
    op.drop_column('fraud_assessments', 'updated_at')
    op.drop_column('documents', 'updated_at')
    op.drop_column('document_access_logs', 'updated_at')
    op.drop_column('consent_records', 'updated_at')
    op.alter_column('claims', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('audit_logs', 'updated_at')
    # ### end Alembic commands ###
