"""add_document_validation_fields

Revision ID: d4e5f6a7b8c9
Revises: cdfe9f7e2021
Create Date: 2026-02-20 20:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4e5f6a7b8c9'
down_revision: Union[str, None] = 'cdfe9f7e2021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add document validation fields
    op.add_column('documents', sa.Column('validation_status', sa.String(length=32), nullable=True))
    op.add_column('documents', sa.Column('validation_reason', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('authenticity_metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('documents', sa.Column('fraud_signal_weight', sa.Numeric(precision=5, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'fraud_signal_weight')
    op.drop_column('documents', 'authenticity_metadata_json')
    op.drop_column('documents', 'validation_reason')
    op.drop_column('documents', 'validation_status')
    # ### end Alembic commands ###
